include:
  - airflow/docker-compose.yaml

services:
  ingestor:
    build: ./ingestor
    volumes:
      - ./ingestor/app:/code/app
    environment:
      - AIRFLOW_URL=http://airflow-webserver:8080
    ports:
      - "8081:80"
